import { Geist, Geist_Mono } from "next/font/google";
import Head from "next/head";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { StateContext } from "./context/StateContext";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "phoneHeads",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <Head>
                <title>phoneHeads</title>
            </Head>

            <body>
                <StateContext>
                    <header>
                        <Navbar />
                    </header>
                    <main className="main-container">
                        {children}
                        <Toaster position="top-center" reverseOrder={false} />
                    </main>
                    <footer>
                        <Footer />
                    </footer>
                </StateContext>
            </body>
        </html>
    );
}
